name: Test artifact download

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Test Ole Super"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.workflow_run.event == 'pull_request' &&
    #   github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        run: echo "in workflow"
      # - name: ci/mkdir
      #   run: mkdir -p ${{github.workspace}}/server/dist/
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: artifacts.yml
          # pr: 22709
          # name: server-dist-artifact
          # # Optional, a directory where to extract artifact(s), defaults to the current directory
          # path: '${{github.workspace}}/server/dist'
          # Optional, defaults to current repo
          repo: mattermost/mattermost-server
          if_no_artifact_found: warn
      - name: ci/mkdir
        run: ls -la ${{github.workspace}}/server/dist/
