name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Test Ole Super"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.workflow_run.event == 'pull_request' &&
    #   github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        run: echo "in workflow"
      - name: ci/mkdir
        run: mkdir -p ${{github.workspace}}/server/dist/
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          # Optional, will get head commit SHA
          pr: 22709
          name: 'server-dist-artifact'
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: ${{github.workspace}}/server/dist/
          # Optional, defaults to current repo
          repo: "https://github.com/mattermost/mattermost-server"
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: false
          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          skip_unpack: false
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: fail
      - name: ci/mkdir
        run: ls -la ${{github.workspace}}/server/dist/
